name: SDK / Label
on:
  pull_request:
  workflow_dispatch:

jobs:
  add-labels:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.head.ref, 'openapi-update-') }}
        with:
          labels: |
            enhancement
