name: SDK / Update OpenAPI

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  api-spec-update:
    name: Update
    runs-on: ubuntu-22.04
    if: ${{ contains(github.repository_owner, 'jellyfin') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Setup Java
        uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # tag=v2
      - name: Set STABLE_API_VERSION
        run: |
          VERSION=$(curl -sL https://repo.jellyfin.org/releases/openapi/jellyfin-openapi-stable.json | jq -r .info.version)
          echo "STABLE_API_VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Update api spec
        run: |
          ./gradlew :openapi-generator:updateApiSpecStable
          ./gradlew apiDump
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.JF_BOT_TOKEN }}
          commit-message: 'Update generated sources to ${{ env.STABLE_API_VERSION }}'
          committer: 'jellyfin-bot'
          author: 'team@jellyfin.org'
          title: 'Update OpenAPI to ${{ env.STABLE_API_VERSION }}'
          labels: enhancement
          branch: 'openapi-update-'
          branch-suffix: 'short-commit-hash'
          delete-branch: true
          body: Automated action that updates the open api spec and generates sources.
